const fs = require("node:fs");
let fails = 0;
function rep(path, anchor, replacement) {
  const s = fs.readFileSync(path, "utf8");
  const i = s.indexOf(anchor);
  if (i < 0) { console.error("ANCHOR-MISS " + path + " :: " + anchor.slice(0, 70)); fails++; return; }
  if (s.indexOf(anchor, i + 1) >= 0) { console.error("ANCHOR-AMBIG " + path + " :: " + anchor.slice(0, 70)); fails++; return; }
  fs.writeFileSync(path, s.slice(0, i) + replacement + s.slice(i + anchor.length));
  console.log("PATCHED " + path + " :: " + anchor.slice(0, 45));
}
const RX = "apps/editor/renderer/index.html";
const MN = "apps/editor/src/main.js";
rep(RX, "let S = null, SEQ = null, FRAME = 0, SEL = new Set(), FPS = 30;", "let S = null, SEQ = null, FRAME = 0, SEL = new Set(), FPS = 30;\nlet VIEW = null;\nfunction viewDur() { return (VIEW && VIEW.dur > 0 ? VIEW.dur : DUR()); }\nfunction viewStart() { return (VIEW && VIEW.start >= 0 ? VIEW.start : 0); }\nwindow.__setZoom = async (s, d) => { VIEW = (d > 0 ? { start: Math.max(s, 0), dur: d } : null); await refresh(); zoomLabel(); };\nfunction zoomLabel() { const el = document.querySelector(\"#zlab\"); if (el && SEQ) el.textContent = (VIEW ? Math.round(DUR() / VIEW.dur * 100) + \"%\" : \"Fit\"); }");
rep(RX, "const durR = DUR(); const stepR = durR > 900 ? 240 : durR > 360 ? 120 : durR > 120 ? 60 : durR > 60 ? 30 : 15;", "const durR = viewDur(), vstR = viewStart(); const stepR = durR > 900 ? 240 : durR > 360 ? 120 : durR > 120 ? 60 : durR > 60 ? 30 : 15; const t0R = Math.ceil(vstR / stepR) * stepR;");
rep(RX, "for (let tf = 0; tf <= durR; tf += stepR)", "for (let tf = t0R; tf <= vstR + durR; tf += stepR)");
rep(RX, "(tf / durR * 100)", "((tf - vstR) / durR * 100)");
rep(RX, "const l = c.startFrame / dur * 100, w = c.durationFrames / dur * 100;", "const l = (c.startFrame - viewStart()) / viewDur() * 100, w = c.durationFrames / viewDur() * 100;");
rep(RX, "(m.startFrame / dur * 100)", "((m.startFrame - viewStart()) / viewDur() * 100)");
rep(RX, "const tov = document.getElementById('textov'), tovt = document.getElementById('textovt');", "const ph0 = document.getElementById('ph'); if (ph0) { const pp = (FRAME - viewStart()) / viewDur() * 100; ph0.style.left = pp + '%'; ph0.style.display = (pp >= 0 && pp <= 100) ? 'block' : 'none'; } const tov = document.getElementById('textov'), tovt = document.getElementById('textovt');");
rep(RX, "const df = Math.round(dx / tl.width * DUR());", "const df = Math.round(dx / tl.width * viewDur());");
rep(RX, "<div id=\"tlbar\"><span>Timeline</span>", "<div id=\"tlbar\"><span>Timeline</span><span class=\"zctl\"><button id=\"zOut\" title=\"Zoom out\">-</button><button id=\"zFit\" title=\"Fit\">Fit</button><button id=\"zIn\" title=\"Zoom in\">+</button><span id=\"zlab\">Fit</span></span>");
rep(RX, "document.addEventListener(\"keydown\", async (e) => {", "document.querySelector(\"#zIn\").addEventListener(\"click\", async () => { const vd = viewDur(); const nd = Math.max(Math.round(vd / 1.5), 30); if (nd >= DUR()) { VIEW = null; } else { VIEW = { start: Math.min(Math.max(Math.round(FRAME - nd / 2), 0), Math.max(DUR() - nd, 0)), dur: Math.min(nd, DUR()) }; } await refresh(); zoomLabel(); });\ndocument.querySelector(\"#zOut\").addEventListener(\"click\", async () => { const vd = viewDur(); const nd = Math.round(vd * 1.5); if (nd >= DUR()) { VIEW = null; } else { const cc = VIEW ? VIEW.start + VIEW.dur / 2 : DUR() / 2; VIEW = { start: Math.min(Math.max(Math.round(cc - nd / 2), 0), Math.max(DUR() - nd, 0)), dur: nd }; } await refresh(); zoomLabel(); });\ndocument.querySelector(\"#zFit\").addEventListener(\"click\", async () => { VIEW = null; await refresh(); zoomLabel(); });\ndocument.addEventListener(\"keydown\", async (e) => {");
rep(RX, "#tlbar .hint{font-weight:400;text-transform:none;letter-spacing:0;color:var(--mut);font-size:11px}", "#tlbar .hint{font-weight:400;text-transform:none;letter-spacing:0;color:var(--mut);font-size:11px}\n.zctl{display:flex;align-items:center;gap:4px;margin-left:auto}\n.zctl button{font-size:11px;padding:2px 9px}\n#zlab{font-size:11px;color:var(--fg3);min-width:40px;text-transform:none;letter-spacing:0}");
const zoomInner = "(async () => { var s0 = await window.palmier.state(); var q0 = s0.sequences[0]; var D = q0.clips.reduce(function(a, c){ return Math.max(a, c.startFrame + c.durationFrames); }, 0) || 90; var s = Math.floor(D / 4), d = Math.floor(D / 2); await window.__setZoom(s, d); await new Promise(function(r){ setTimeout(r, 400); }); var first = null; document.querySelectorAll('.clip').forEach(function(el){ if (!first && el.dataset && el.dataset.id) first = el; }); if (!first) return 'no-clip'; var st1 = await window.palmier.state(); var c0 = st1.sequences[0].clips.find(function(c){ return c.id === first.dataset.id; }); var expL = (c0.startFrame - s) / d * 100, gotL = parseFloat(first.style.left); var sk = document.querySelector('#seek'); sk.value = s + Math.floor(d / 2); sk.dispatchEvent(new Event('input')); await new Promise(function(r){ setTimeout(r, 600); }); var ph = document.querySelector('#tl .ph'); var phL = ph ? parseFloat(ph.style.left) : NaN; var phVis = ph ? getComputedStyle(ph).display !== 'none' : false; await window.__setZoom(0, 0); await new Promise(function(r){ setTimeout(r, 300); }); return 'clip:' + (Math.abs(expL - gotL) < 0.05) + ' ph:' + (Math.abs(phL - 50) < 1.5 && phVis) + ' n=' + document.querySelectorAll('.clip').length; })()";
rep(MN, "console.log(\"SMOKE-KEYS\",", "console.log(\"SMOKE-ZOOM\", await win.webContents.executeJavaScript(\"" + zoomInner + "\"));\n    console.log(\"SMOKE-KEYS\",");
if (fails > 0) { console.error("PATCH-FAILED"); process.exit(1); } else console.log("ZOOM-OK");
