import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createProject, createSequence, addTrack } from "../model.js";
import { EditorStore } from "../store.js";
import { buildFfmpegArgs, exportSequence, validateExport } from "../export.js";
const fix = (n: string): string => join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "..", "tests", "fixtures", n);
test("crop validated and rendered", async () => {
  const fps = { num: 30, den: 1 };
  const st = new EditorStore(createProject("cr"));
  const seq = createSequence(st.project, "s", fps, 320, 240);
  const v1 = addTrack(seq, "video", "V1");
  st.addMedia({ path: fix("sample-av.mp4"), kind: "video", name: "v", durationFrames: 90, fps });
  const id = st.placeClip(seq.id, v1.id, { kind: "video", assetId: st.project.media[0].id, startFrame: 0, durationFrames: 90, name: "v" }).ids[0];
  assert.ok(!st.setCrop(seq.id, id, { l: 0.6, t: 0, r: 0.6, b: 0 }).ok);
  assert.ok(st.setCrop(seq.id, id, { l: 0.25, t: 0, r: 0.25, b: 0 }).ok);
  assert.ok(st.setCrop(seq.id, id, { l: 0.25, t: 0, r: 0.25, b: 0 }).noop);
  const dir = mkdtempSync(join(tmpdir(), "palm-cr-"));
  const plan = await buildFfmpegArgs(st.project, seq, join(dir, "o.mp4"));
  const fc: string = plan.args[plan.args.indexOf("-filter_complex") + 1];
  assert.ok(fc.includes("crop=w=iw*0.5:h=ih*1"), "crop fractions");
  const out = join(dir, "c.mp4");
  const ex = await exportSequence(st.project, seq.id, out);
  const v = await validateExport(out, ex.durationSec, true);
  assert.ok(v.ok, v.details);
});
