import test from "node:test";
import assert from "node:assert/strict";
import { createProject, createSequence, addTrack } from "../model.js";
import { EditorStore } from "../store.js";
test("duplicateClips copies land at track ends with fresh links", () => {
  const fps = { num: 30, den: 1 };
  const st = new EditorStore(createProject("dup"));
  const seq = createSequence(st.project, "s", fps, 320, 240);
  const v1 = addTrack(seq, "video", "V1");
  const a = st.placeClip(seq.id, v1.id, { kind: "text", startFrame: 0, durationFrames: 30, name: "t", text: "Hi" }).ids[0];
  const b = st.placeClip(seq.id, v1.id, { kind: "text", startFrame: 30, durationFrames: 30, name: "u", text: "Yo" }).ids[0];
  assert.ok(!st.duplicateClips(seq.id, []).ok);
  assert.ok(!st.duplicateClips(seq.id, ["missing"]).ok);
  assert.ok(st.setKeyframe(seq.id, a, "opacity", { frame: 5, value: 0.3 }).ok);
  assert.ok(st.linkClips(seq.id, [a, b]).ok);
  const r = st.duplicateClips(seq.id, [a, b]);
  assert.ok(r.ok);
  assert.equal(r.ids.length, 2);
  const clips = st.project.sequences[0].clips;
  assert.equal(clips.length, 4);
  const ca = clips.find((c) => c.id === r.ids[0])!;
  const cb = clips.find((c) => c.id === r.ids[1])!;
  assert.equal(ca.text, "Hi");
  assert.equal(ca.startFrame, 60);
  assert.equal(cb.startFrame, 90);
  assert.deepEqual(ca.opacityKeys, [{ frame: 5, value: 0.3, interpolation: "linear" }]);
  assert.ok(ca.linkGroup);
  assert.equal(ca.linkGroup, cb.linkGroup);
  const origA = clips.find((c) => c.id === a)!;
  assert.ok(origA.linkGroup !== ca.linkGroup);
  assert.ok(st.undo());
  assert.equal(st.project.sequences[0].clips.length, 2);
  assert.ok(st.redo());
  assert.equal(st.project.sequences[0].clips.length, 4);
});
