import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createProject, createSequence, addTrack } from "../model.js";
import { EditorStore } from "../store.js";
import { buildFfmpegArgs, exportSequence, validateExport } from "../export.js";
const fix = (n: string): string => join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "..", "tests", "fixtures", n);
test("text style validated, aligned, boxed in export", async () => {
  const fps = { num: 30, den: 1 };
  const st = new EditorStore(createProject("ts"));
  const seq = createSequence(st.project, "s", fps, 320, 240);
  const v1 = addTrack(seq, "video", "V1");
  const v2 = addTrack(seq, "video", "V2");
  st.addMedia({ path: fix("sample-av.mp4"), kind: "video", name: "v", durationFrames: 90, fps });
  st.placeClip(seq.id, v1.id, { kind: "video", assetId: st.project.media[0].id, startFrame: 0, durationFrames: 90, name: "v" });
  const id = st.placeClip(seq.id, v2.id, { kind: "text", startFrame: 0, durationFrames: 90, name: "t", text: "Hi" }).ids[0];
  assert.ok(!st.setTextStyle(seq.id, id, { textAlign: "sideways" as never }).ok);
  assert.ok(!st.setTextStyle(seq.id, id, { fontSize: 4 }).ok);
  assert.ok(st.setTextStyle(seq.id, id, { textAlign: "left", textBg: true }).ok);
  assert.ok(st.setTextStyle(seq.id, id, { textAlign: "left", textBg: true }).noop);
  const dir = mkdtempSync(join(tmpdir(), "palm-ts-"));
  const plan = await buildFfmpegArgs(st.project, seq, join(dir, "o.mp4"));
  const fc: string = plan.args[plan.args.indexOf("-filter_complex") + 1];
  assert.ok(fc.includes("x=20"), "left align");
  assert.ok(fc.includes("box=1"), "bg box");
  const out = join(dir, "t.mp4");
  const ex = await exportSequence(st.project, seq.id, out);
  const v = await validateExport(out, ex.durationSec, true);
  assert.ok(v.ok, v.details);
});

import { resolveFontFile } from '../model.js';
test('text font family validated, undoable, honored in export', async () => {
  const fps = { num: 30, den: 1 };
  const st = new EditorStore(createProject('ff'));
  const seq = createSequence(st.project, 's', fps, 320, 240);
  const v1 = addTrack(seq, 'video', 'V1');
  const v2 = addTrack(seq, 'video', 'V2');
  st.addMedia({ path: fix('sample-av.mp4'), kind: 'video', name: 'v', durationFrames: 90, fps });
  const vclip = st.placeClip(seq.id, v1.id, { kind: 'video', assetId: st.project.media[0].id, startFrame: 0, durationFrames: 90, name: 'v' }).ids[0];
  assert.ok(!st.setTextStyle(seq.id, vclip, { fontFamily: 'arial' }).ok);
  const id = st.placeClip(seq.id, v2.id, { kind: 'text', startFrame: 0, durationFrames: 90, name: 't', text: 'Ff' }).ids[0];
  assert.ok(!st.setTextStyle(seq.id, id, { fontFamily: 'comic' }).ok);
  assert.ok(st.setTextStyle(seq.id, id, { fontFamily: 'times' }).ok);
  assert.ok(st.setTextStyle(seq.id, id, { fontFamily: 'times' }).noop);
  assert.equal(st.project.sequences[0].clips.find((c) => c.id === id)!.fontFamily, 'times');
  assert.ok(st.undo());
  assert.equal(st.project.sequences[0].clips.find((c) => c.id === id)!.fontFamily, undefined);
  assert.ok(st.redo());
  const dir = mkdtempSync(join(tmpdir(), 'palm-ff-'));
  const plan = await buildFfmpegArgs(st.project, seq, join(dir, 'o.mp4'));
  const fc = plan.args[plan.args.indexOf('-filter_complex') + 1];
  if (resolveFontFile('times')) assert.ok(fc.indexOf('fontfile=') >= 0, 'fontfile in graph');
  else assert.ok(fc.indexOf('fontfile=') < 0, 'honest fallback without system fonts');
  const out = join(dir, 'f.mp4');
  const ex = await exportSequence(st.project, seq.id, out);
  const v = await validateExport(out, ex.durationSec, true);
  assert.ok(v.ok, v.details);
});

test('text bold italic resolve to variant files, validated, exported', async () => {
  const fps = { num: 30, den: 1 };
  const st = new EditorStore(createProject('bi'));
  const seq = createSequence(st.project, 's', fps, 320, 240);
  const v1 = addTrack(seq, 'video', 'V1');
  const v2 = addTrack(seq, 'video', 'V2');
  st.addMedia({ path: fix('sample-av.mp4'), kind: 'video', name: 'v', durationFrames: 90, fps });
  st.placeClip(seq.id, v1.id, { kind: 'video', assetId: st.project.media[0].id, startFrame: 0, durationFrames: 90, name: 'v' });
  const id = st.placeClip(seq.id, v2.id, { kind: 'text', startFrame: 0, durationFrames: 90, name: 't', text: 'Bi' }).ids[0];
  assert.ok(!st.setTextStyle(seq.id, id, { fontBold: 'yes' as never }).ok);
  assert.ok(!st.setTextStyle(seq.id, id, { fontItalic: 1 as never }).ok);
  assert.ok(st.setTextStyle(seq.id, id, { fontFamily: 'arial', fontBold: true, fontItalic: true }).ok);
  assert.ok(st.setTextStyle(seq.id, id, { fontFamily: 'arial', fontBold: true, fontItalic: true }).noop);
  const c = st.project.sequences[0].clips.find((x) => x.id === id)!;
  assert.equal(c.fontBold, true);
  assert.equal(c.fontItalic, true);
  const ff = resolveFontFile('arial', true, true);
  if (ff) assert.ok(ff.toLowerCase().endsWith('arialbi.ttf'), 'bolditalic variant, got ' + ff);
  else assert.ok(!resolveFontFile('arial'), 'honest fallback only when regular missing too');
  assert.ok(st.undo());
  assert.equal(st.project.sequences[0].clips.find((x) => x.id === id)!.fontBold, undefined);
  assert.ok(st.redo());
  const dir = mkdtempSync(join(tmpdir(), 'palm-bi-'));
  const plan = await buildFfmpegArgs(st.project, seq, join(dir, 'o.mp4'));
  const fc = plan.args[plan.args.indexOf('-filter_complex') + 1];
  if (resolveFontFile('arial', true, true)) assert.ok(fc.indexOf('fontfile=') >= 0, 'variant fontfile in graph');
  const out = join(dir, 'b.mp4');
  const ex = await exportSequence(st.project, seq.id, out);
  const v = await validateExport(out, ex.durationSec, true);
  assert.ok(v.ok, v.details);
});

test('text shadow and outline validated and burned into export', async () => {
  const fps = { num: 30, den: 1 };
  const st = new EditorStore(createProject('so'));
  const seq = createSequence(st.project, 's', fps, 320, 240);
  const v1 = addTrack(seq, 'video', 'V1');
  const v2 = addTrack(seq, 'video', 'V2');
  st.addMedia({ path: fix('sample-av.mp4'), kind: 'video', name: 'v', durationFrames: 90, fps });
  st.placeClip(seq.id, v1.id, { kind: 'video', assetId: st.project.media[0].id, startFrame: 0, durationFrames: 90, name: 'v' });
  const id = st.placeClip(seq.id, v2.id, { kind: 'text', startFrame: 0, durationFrames: 90, name: 't', text: 'Edge' }).ids[0];
  assert.ok(!st.setTextStyle(seq.id, id, { textShadow: 'x' as never }).ok);
  assert.ok(st.setTextStyle(seq.id, id, { textShadow: true, textOutline: true }).ok);
  assert.ok(st.setTextStyle(seq.id, id, { textShadow: true, textOutline: true }).noop);
  const c = st.project.sequences[0].clips.find((x) => x.id === id)!;
  assert.equal(c.textShadow, true);
  assert.equal(c.textOutline, true);
  const dir = mkdtempSync(join(tmpdir(), 'palm-so-'));
  const plan = await buildFfmpegArgs(st.project, seq, join(dir, 'o.mp4'));
  const fc: string = plan.args[plan.args.indexOf('-filter_complex') + 1];
  assert.ok(fc.indexOf('shadowcolor=black') >= 0, 'shadow in graph');
  assert.ok(fc.indexOf('borderw=2') >= 0, 'outline in graph');
  const out = join(dir, 's.mp4');
  const ex = await exportSequence(st.project, seq.id, out);
  const v = await validateExport(out, ex.durationSec, true);
  assert.ok(v.ok, v.details);
});
