import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createProject, createSequence, addTrack } from "../model.js";
import { EditorStore } from "../store.js";
import { exportSequence, validateExport } from "../export.js";
const fix = (n: string): string => join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "..", "tests", "fixtures", n);
const meanVol = (file: string): number => {
  const r = spawnSync("ffmpeg", ["-v", "info", "-i", file, "-af", "volumedetect", "-f", "null", "-"], { encoding: "utf8" });
  const m = /mean_volume: (-?[\d.]+) dB/.exec(r.stderr);
  if (!m) throw new Error("no mean_volume in " + String(r.stderr).slice(-300));
  return Number(m[1]);
};
test("track volume flag validated, undoable, audible in export", async () => {
  const fps = { num: 30, den: 1 };
  const st = new EditorStore(createProject("tv"));
  const seq = createSequence(st.project, "s", fps, 320, 240);
  const v1 = addTrack(seq, "video", "V1");
  const a1 = addTrack(seq, "audio", "A1");
  st.addMedia({ path: fix("sample-av.mp4"), kind: "video", name: "v", durationFrames: 90, fps });
  st.addMedia({ path: fix("sample-audio.wav"), kind: "audio", name: "a", durationFrames: 90, fps });
  const vid = st.placeClip(seq.id, v1.id, { kind: "video", assetId: st.project.media[0].id, startFrame: 0, durationFrames: 90, name: "v" }).ids[0];
  assert.ok(st.setVolume(seq.id, vid, 1, true).ok);
  st.placeClip(seq.id, a1.id, { kind: "audio", assetId: st.project.media[1].id, startFrame: 0, durationFrames: 90, name: "a" });
  assert.ok(!st.setTrackFlags(seq.id, a1.id, { volume: -1 }).ok);
  assert.ok(!st.setTrackFlags(seq.id, a1.id, { volume: 5 }).ok);
  assert.ok(st.setTrackFlags(seq.id, a1.id, { volume: 0.25 }).ok);
  assert.ok(st.setTrackFlags(seq.id, a1.id, { volume: 0.25 }).noop);
  assert.equal(st.project.sequences[0].tracks.find((t) => t.id === a1.id)!.volume, 0.25);
  const dir = mkdtempSync(join(tmpdir(), "palm-tv-"));
  const low = join(dir, "low.mp4");
  const ex1 = await exportSequence(st.project, seq.id, low);
  assert.ok((await validateExport(low, ex1.durationSec, true)).ok);
  const mLow = meanVol(low);
  assert.ok(st.setTrackFlags(seq.id, a1.id, { volume: 1 }).ok);
  const full = join(dir, "full.mp4");
  const ex2 = await exportSequence(st.project, seq.id, full);
  assert.ok((await validateExport(full, ex2.durationSec, true)).ok);
  const mFull = meanVol(full);
  assert.ok(mFull - mLow > 8, "track gain audible: full=" + mFull + " low=" + mLow);
  assert.ok(st.undo());
  assert.equal(st.project.sequences[0].tracks.find((t) => t.id === a1.id)!.volume, 0.25);
});
