import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createProject, createSequence, addTrack, videoClipAt } from "../model.js";
import { EditorStore } from "../store.js";
import { exportSequence, validateExport } from "../export.js";
const fix = (n: string): string => join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "..", "tests", "fixtures", n);
test("track mute/hide/lock semantics", async () => {
  const fps = { num: 30, den: 1 };
  const st = new EditorStore(createProject("t"));
  const seq = createSequence(st.project, "s", fps, 320, 240);
  const v1 = addTrack(seq, "video", "V1");
  const a1 = addTrack(seq, "audio", "A1");
  st.addMedia({ path: fix("sample-av.mp4"), kind: "video", name: "v", durationFrames: 90, fps });
  st.addMedia({ path: fix("sample-audio.wav"), kind: "audio", name: "a", durationFrames: 90, fps });
  const vc = st.placeClip(seq.id, v1.id, { kind: "video", assetId: st.project.media[0].id, startFrame: 0, durationFrames: 90, name: "v" }).ids[0];
  st.placeClip(seq.id, a1.id, { kind: "audio", assetId: st.project.media[1].id, startFrame: 0, durationFrames: 90, name: "a" });
  assert.ok(!st.setTrackFlags(seq.id, v1.id, { locked: "x" } as never).ok);
  assert.ok(st.setTrackFlags(seq.id, v1.id, { locked: true }).ok);
  assert.ok(!st.moveClip(seq.id, vc, v1.id, 10).ok);
  assert.ok(st.setTrackFlags(seq.id, v1.id, { locked: false }).ok);
  assert.ok(st.setTrackFlags(seq.id, v1.id, { hidden: true }).ok);
  assert.equal(videoClipAt(seq, 10), undefined);
  assert.ok(st.setTrackFlags(seq.id, v1.id, { hidden: false }).ok);
  assert.ok(videoClipAt(seq, 10));
  assert.ok(st.setTrackFlags(seq.id, a1.id, { muted: true }).ok);
  const dir = mkdtempSync(join(tmpdir(), "palm-tf-"));
  const out = join(dir, "o.mp4");
  const ex = await exportSequence(st.project, seq.id, out);
  const v = await validateExport(out, ex.durationSec, false);
  assert.ok(v.ok, v.details);
});
